version: 0.2

phase:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installation phase, nothing special yet"
  build:
    commands:
      - echo "Building and zipping all lambda functions"
    
      - cd createGame
      - rm -f createGame.zip
      - zip createGame.zip createGame.py
      - aws s3 cp createGame.zip s3://aws-cardgame-metrics-bucket/lambdas/createGame.zip
      - aws lambda update-function-code --function-name createGame --zip-file fileb://createGame.zip
      - cd ..

      - cd joinGame
      - rm -f joinGame.zip
      - zip joinGame.zip joinGame.py
      - aws s3 cp joinGame.zip s3://aws-cardgame-metrics-bucket/lambdas/joinGame.zip
      - aws lambda update-function-code --function-name joinGame --zip-file fileb://joinGame.zip  
      - cd ..

      - cd startGame
      - rm -f startGame.zip
      - zip startGame.zip startGame.py
      - aws s3 cp startGame.zip s3://aws-cardgame-metrics-bucket/lambdas/startGame.zip
      - aws lambda update-function-code --function-name startGame --zip-file fileb://startGame.zip
      - cd ..

      - cd endGame
      - rm -f endGame.zip
      - zip endGame.zip endGame.py
      - aws s3 cp endGame.zip s3://aws-cardgame-metrics-bucket/lambdas/endGame.zip
      - aws lambda update-function-code --function-name endGame --zip-file fileb://endGame.zip
      - cd ..

      - cd gameStats
      - rm -f gameStats.zip
      - zip gameStats.zip gameStats.py
      - aws s3 cp gameStats.zip s3://aws-cardgame-metrics-bucket/lambdas/gameStats.zip
      - aws lambda update-function-code --function-name gameStats --zip-file fileb://gameStats.zip
      - cd ..

      - cd drawCard
      - rm -f drawCard.zip
      - zip drawCard.zip drawCard.py
      - aws s3 cp drawCard.zip s3://aws-cardgame-metrics-bucket/lambdas/drawCard.zip
      - aws lambda update-function-code --function-name drawCard --zip-file fileb://drawCard.zip
      - cd ..

      - cd throwCard
      - rm -f throwCard.zip
      - zip throwCard.zip throwCard.py
      - aws lambda update-function-code --function-name throwCard --zip-file fileb://throwCard.zip
      - aws s3 cp throwCard.zip s3://aws-cardgame-metrics-bucket/lambdas/throwCard.zip
      - cd ..

      - cd sendChatMessage
      - rm -f sendChatMessage.zip
      - zip sendChatMessage.zip sendChatMessage.py
      - aws lambda update-function-code --function-name sendChatMessage --zip-file fileb://sendChatMessage.zip
      - aws s3 cp sendChatMessage.zip s3://aws-cardgame-metrics-bucket/lambdas/sendChatMessage.zip
      - cd ..

      - cd getChatMessage
      - rm -f getChatMessage.zip
      - zip getChatMessage.zip getChatMessage.py
      - aws lambda update-function-code --function-name getChatMessage --zip-file fileb://getChatMessage.zip
      - aws s3 cp getChatMessage.zip s3://aws-cardgame-metrics-bucket/lambdas/getChatMessage.zip
      - cd ..
  
  post_build:
    commands:
      - echo "All Lambda functions updated and zipped successfully."